name: Gatling Load Tests

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  gatling:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build jar
        run: ./gradlew clean bootJar --no-daemon

      - name: Start Spring Boot app (jar, background)
        run: |
          nohup java -jar build/libs/*-SNAPSHOT.jar &> bootrun.log & echo $! > .app.pid

      - name: Wait for app ready
        run: |
          set -e
          TIMEOUT=60
          SLEEP=2
          URL="http://localhost:8080/actuator/health"
          SECONDS=0
          until curl -sSf "$URL" > /dev/null 2>&1; do
            sleep $SLEEP
            SECONDS=$((SECONDS + SLEEP))
            if [ $SECONDS -ge $TIMEOUT ]; then
              tail -n +1 bootrun.log || true
              exit 1
            fi
          done

      - name: Run Gatling simulation
        run: ./gradlew gatlingRun --no-daemon --simulation "com.GreetingHistorySimulation"
        env:
          GRADLE_OPTS: "-Xmx3g"

      - name: Upload Gatling report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gatling-report
          path: build/reports/gatling/**

      - name: Upload bootrun log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: bootrun-log
          path: bootrun.log

      - name: Stop Spring Boot app
        if: always()
        run: |
          if [ -f .app.pid ]; then kill $(cat .app.pid) || true; fi
